# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

RUN npm install -g pnpm@10.18.1

# Install app dependencies
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --ignore-scripts

# Copy source code
COPY . .

# Build the project
RUN pnpm build

# Expose port if needed (optional, not specified in source, so leaving as is)

# Command to run the MCP server
CMD ["node", "dist/index.js"]
