import z from "zod";

// Sales Dialer Calls Schemas
export const ListSalesDialerCallsSchema = {
  campaign_id: z
    .number()
    .optional()
    .describe(
      "Campaign ID of the Campaign for which you wish to fetch the calls. You can find the Campaign ID in the Campaigns tab in your Sales Dialer account below the name of each Campaign. Please use only the numerical part as the ID."
    ),
  fetch_ai_data: z
    .boolean()
    .optional()
    .describe(
      "Set fetch_ai_data to true to fetch coaching data by Justcall AI. Default entry is false"
    ),
  from_datetime: z
    .string()
    .optional()
    .describe(
      "Datetime in yyyy-mm-dd hh:mm:ss or yyyy-mm-dd format starting from when the calls are to be fetched in user's timezone."
    ),
  to_datetime: z
    .string()
    .optional()
    .describe(
      "Datetime in yyyy-mm-dd hh:mm:ss or yyyy-mm-dd format till when the calls are to be fetched in user's timezone."
    ),
  contact_number: z
    .number()
    .optional()
    .describe(
      "Number of the contact for which calls are to be fetched. Important: Please provide a valid contact number with country code."
    ),
  sales_dialer_number: z
    .number()
    .optional()
    .describe("Sales Dialer number for which the calls are to be fetched."),
  agent_id: z
    .number()
    .optional()
    .describe(
      "ID of the agent for whom the calls are to be fetched. Agent ID can be accessed using List all users API."
    ),
  call_type: z
    .enum([
      "OUTGOING_ANSWERED_CALL",
      "OUTGOING_HUMAN_ANSWERED",
      "OUTGOING_MACHINE_ANSWERED",
      "OUTGOING_UNANSWERED_CALL",
      "OUTGOING_FAILED_CALL",
      "OUTGOING_RESTRICTED_CALL",
      "OUTGOING_BLOCKED_CALL",
      "OUTGOING_CANCELLED_CALL",
      "OUTGOING_ABANDONED_CALL",
    ])
    .optional()
    .describe(
      "Enter the type of calls (answered, unanswered, abandoned) that need to be fetched."
    ),
  page: z
    .number()
    .optional()
    .describe("Page number for which calls are to be fetched"),
  per_page: z
    .number()
    .optional()
    .describe(
      "Number of calls to be fetched per page. Default value is 20 and maximum value is 100."
    ),
  sort: z
    .enum(["id", "datetime"])
    .optional()
    .describe(
      "Select a parameter to sort the order of calls. By default we apply sorting on id field."
    ),
  order: z
    .enum(["asc", "desc"])
    .optional()
    .describe(
      "Order in which the calls list should appear based on the 'sort' parameter selected above"
    ),
  last_call_id_fetched: z
    .number()
    .optional()
    .describe(
      "Id of the last call fetched in the previous query. This Id ensures that you won't receive any duplicate data when using the 'next_page_link' parameter."
    ),
};

export const GetSalesDialerCallSchema = {
  id: z.number().describe("Unique id of the call generated by Sales Dialer"),
  fetch_ai_data: z
    .boolean()
    .optional()
    .describe(
      "Set fetch_ai_data to true to fetch coaching data by Justcall AI. Default entry is false."
    ),
};
