import z from "zod";

// JustCall AI Schemas for Calls
export const ListCallsAiDataSchema = {
  platform: z
    .enum(["justcall", "sales_dialer"])
    .optional()
    .describe("Select the platform to retrieve associated call details."),
  phone_number: z
    .number()
    .optional()
    .describe(
      "The phone number (JustCall or Sales Dialer) for which the list of AI-generated call data will be fetched. The number must be linked to the selected platform. If no platform is specified, the default is justcall."
    ),
  fetch_transcription: z
    .boolean()
    .optional()
    .describe(
      "Set fetch_transcription to true to fetch the transcription generated by JustCall AI for your call. Default entry is false."
    ),
  fetch_summary: z
    .boolean()
    .optional()
    .describe(
      "Set fetch_summary to true to fetch the summary generated by JustCall AI for your call. Default entry is true."
    ),
  fetch_ai_insights: z
    .boolean()
    .optional()
    .describe(
      "Set fetch_ai_insights to true to fetch the coaching insights generated by JustCall AI for your call. Default entry is true."
    ),
  fetch_action_items: z
    .boolean()
    .optional()
    .describe(
      "Set fetch_action_items to true to fetch the action items generated by JustCall AI for your call. Default entry is true."
    ),
  fetch_smart_chapters: z
    .boolean()
    .optional()
    .describe(
      "Set fetch_smart_chapters to true to fetch the smart chapters generated by JustCall AI for your call. Default entry is true."
    ),
  agent_id: z
    .number()
    .optional()
    .describe(
      "ID of the agent for whom the AI data for calls are to be fetched. Agent ID can be accessed using List all users API."
    ),
  from_datetime: z
    .string()
    .optional()
    .describe(
      "Datetime in yyyy-mm-dd hh:mm:ss or yyyy-mm-dd format starting from when the calls AI data are to be fetched in user's timezone."
    ),
  to_datetime: z
    .string()
    .optional()
    .describe(
      "Datetime in yyyy-mm-dd hh:mm:ss or yyyy-mm-dd format till when the calls AI data are to be fetched in user's timezone."
    ),
  page: z
    .number()
    .optional()
    .describe("Page number for which calls are to be fetched."),
  per_page: z
    .number()
    .optional()
    .describe(
      "Number count of calls to be fetched per page. Default value is 10 and maximum value is 20."
    ),
  order: z
    .enum(["asc", "desc"])
    .optional()
    .describe(
      "Order in which the calls should appear based on 'Date created'. ASC: Older data will appear first followed by recent one. DESC: Recent data will appear first followed by older one."
    ),
};

export const GetCallAiDataSchema = {
  id: z.number().describe("Unique id of the call generated by JustCall"),
  platform: z
    .enum(["justcall", "sales_dialer"])
    .optional()
    .describe("Select the platform to retrieve associated call details."),
  fetch_transcription: z
    .boolean()
    .optional()
    .describe(
      "Set fetch_transcription to true to fetch the transcription generated by JustCall AI for your call. Default entry is false."
    ),
  fetch_summary: z
    .boolean()
    .optional()
    .describe(
      "Set fetch_summary to true to fetch the summary generated by JustCall AI for your call. Default entry is true."
    ),
  fetch_ai_insights: z
    .boolean()
    .optional()
    .describe(
      "Set fetch_ai_insights to true to fetch the coaching insights generated by JustCall AI for your call. Default entry is true."
    ),
  fetch_action_items: z
    .boolean()
    .optional()
    .describe(
      "Set fetch_action_items to true to fetch the action items generated by JustCall AI for your call. Default entry is true."
    ),
  fetch_smart_chapters: z
    .boolean()
    .optional()
    .describe(
      "Set fetch_smart_chapters to true to fetch the smart chapters generated by JustCall AI for your call. Default entry is true."
    ),
};

// JustCall AI Schemas for Meetings
export const ListMeetingsAiDataSchema = {
  platform: z
    .enum(["zoom", "google_meet"])
    .optional()
    .describe("Select the platform to retrieve associated meeting details."),
  meeting_id: z
    .string()
    .optional()
    .describe(
      "Filter meeting instances based on the Id of the meeting. This Id is unique for each meeting URL and can have multiple instances recorded under it for recurring events under the same URL."
    ),
  fetch_transcription: z
    .boolean()
    .optional()
    .describe(
      "Set fetch_transcription to true to fetch the transcription generated by JustCall AI for your meeting instances. Default entry is false. Please note that the list of speakers is only returned along with the transcription hence it will only appear when fetch_transcription is set to true."
    ),
  fetch_summary: z
    .boolean()
    .optional()
    .describe(
      "Set fetch_summary to true to fetch the summary generated by JustCall AI for your meeting. Default entry is true."
    ),
  fetch_ai_insights: z
    .boolean()
    .optional()
    .describe(
      "Set fetch_ai_insights to true to fetch the coaching insights generated by JustCall AI for your meeting. Default entry is true."
    ),
  fetch_smart_chapters: z
    .boolean()
    .optional()
    .describe(
      "Set fetch_smart_chapters to true to fetch the smart chapters generated by JustCall AI for your meeting. Default entry is true."
    ),
  agent_id: z
    .number()
    .optional()
    .describe(
      "ID of the agent for whom the AI data for meetings are to be fetched. Agent ID can be accessed using List all users API."
    ),
  from_datetime: z
    .string()
    .optional()
    .describe(
      "Datetime in yyyy-mm-dd hh:mm:ss or yyyy-mm-dd format starting from when the meetings AI data are to be fetched in user's timezone."
    ),
  to_datetime: z
    .string()
    .optional()
    .describe(
      "Datetime in yyyy-mm-dd hh:mm:ss or yyyy-mm-dd format till when the meetings AI data are to be fetched in user's timezone."
    ),
  page: z
    .number()
    .optional()
    .describe("Page number for which meetings are to be fetched."),
  per_page: z
    .number()
    .optional()
    .describe(
      "Number count of meetings to be fetched per page. Default value is 10 and maximum value is 20."
    ),
  order: z
    .enum(["asc", "desc"])
    .optional()
    .describe(
      "Order in which the meetings should appear based on 'Date created'. ASC: Older data will appear first followed by recent one. DESC: Recent data will appear first followed by older one."
    ),
};

export const GetMeetingAiDataSchema = {
  instance_sid: z
    .string()
    .describe("Unique sid of the meeting instance generated by JustCall"),
  fetch_transcription: z
    .boolean()
    .optional()
    .describe(
      "Set fetch_transcription to true to fetch the transcription generated by JustCall AI for your meeting instances. Default entry is false. Please note that the list of speakers is only returned along with the transcription hence it will only appear when fetch_transcription is set to true."
    ),
  fetch_summary: z
    .boolean()
    .optional()
    .describe(
      "Set fetch_summary to true to fetch the summary generated by JustCall AI for your meeting. Default entry is true."
    ),
  fetch_ai_insights: z
    .boolean()
    .optional()
    .describe(
      "Set fetch_ai_insights to true to fetch the coaching insights generated by JustCall AI for your meeting. Default entry is true."
    ),
  fetch_smart_chapters: z
    .boolean()
    .optional()
    .describe(
      "Set fetch_smart_chapters to true to fetch the smart chapters generated by JustCall AI for your meeting. Default entry is true."
    ),
};
