import z from "zod";

// User Groups Schemas
export const ListUserGroupsSchema = {
  per_page: z
    .number()
    .optional()
    .describe(
      "Number of user group records to be fetched per page. Default value is 50 and maximum value is 100."
    ),
  page: z
    .number()
    .optional()
    .describe(
      "Page number for which user group records are to be fetched. Default value is 0."
    ),
  order: z
    .enum(["asc", "desc"])
    .optional()
    .describe(
      "Order in which the user group records should appear based on the user group Id. Default value is desc."
    ),
};

export const GetUserGroupSchema = {
  id: z
    .number()
    .describe("Unique id of the user group as generated by JustCall"),
};
