import z from "zod";

// User Schemas
export const ListUsersSchema = {
  available: z
    .boolean()
    .optional()
    .describe(
      "Use available=true to get only those agents that are available as per their working hours in JustCall. By default, we will provide data for all agents irrespective of their availability."
    ),
  group_id: z
    .number()
    .optional()
    .describe(
      "Filter agents based on the User Groups they belong to in JustCall."
    ),
  role: z
    .string()
    .optional()
    .describe("Filter agents based on the role they are assigned in JustCall."),
  page: z
    .number()
    .optional()
    .describe("Page number for which user records are to be fetched"),
  per_page: z
    .number()
    .optional()
    .describe(
      "Number of user records to be fetched per page. Default value is 50 and maximum value is 100."
    ),
  order: z
    .enum(["asc", "desc"])
    .optional()
    .describe(
      "Order in which the user records should appear based on the agent_id"
    ),
};

export const GetUserSchema = {
  id: z.number().describe("Unique Id of the agent (JustCall user)"),
};

export const UpdateUserAvailabilitySchema = {
  agent_id: z
    .number()
    .describe(
      "Unique id of the agent (JustCall user) as generated by JustCall."
    ),
  is_available: z
    .boolean()
    .describe(
      "Enter true to set user as 'available' and false to set as 'unavailable'."
    ),
  unavailability_reason: z
    .string()
    .optional()
    .describe(
      "Enter the unavailability reason for the user. Find reasons added to your account here - https://app.justcall.io/apex/settings. Please note that only the reasons added to your account can be sent in the request."
    ),
};
